apiVersion: audit.k8s.io/v1 # This is required.
kind: Policy
rules:
  - level: RequestResponse
    resources:
    - group: "flowcontrol.apiserver.k8s.io"
      resources: ["flowschemas"]
      version: "v1beta2"
  - level: Metadata
    resources:
    - group: "flowcontrol.apiserver.k8s.io"
      resources: ["flowschemas"]
      version: "v1beta2"
  - level: Request
    resources:
    - group: "flowcontrol.apiserver.k8s.io"
      resources: ["flowschemas"]
      version: "v1beta2"
