apiVersion: audit.k8s.io/v1 # This is required.
kind: Policy
# Don't generate audit events for all requests in RequestReceived stage.
rules:
  # Log pod changes at RequestResponse level
  - level: RequestResponse
    resources:
    - group: "flowcontrol.apiserver.k8s.io"
      resources: ["flowschemas"]
    verbs: ["*"]
    version: "v1beta2"
  - level: Metadata
    resources:
    - group: "flowcontrol.apiserver.k8s.io"
      resources: ["flowschemas"]
    verbs: ["*"]
    version: "v1beta2"
  - level: Request
    resources:
    - group: "flowcontrol.apiserver.k8s.io"
      resources: ["flowschemas"]
    verbs: ["*"]
    version: "v1beta2"
